CONTIKI = /opt/contiki-ng

CONTIKI_PROJECT = toggle-shell

CONTIKI_TARGET_SOURCEFILES += bmpx8x.c
CONTIKI_TARGET_SOURCEFILES += bme280-arch.c

MODULES += arch/dev/bme280

all: $(CONTIKI_PROJECT)

PLATFORMS_ONLY = zoul



include $(CONTIKI)/Makefile.include
